<h1> Credit Card Fraud Detection :</h1>

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [42]:
ccdf=pd.read_csv("creditcard.csv")

In [43]:
ccdf.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [44]:
ccdf.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

<h3>DATA PREPROCESSING :</h3>

In [45]:
ccdf.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [46]:
ccdf['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

<h4>We observe that there is an imbalance in our dataset hence we redefine our Dataframe :</h4>

In [47]:
normal=ccdf[ccdf.Class==0]

In [48]:
fraud=ccdf[ccdf.Class==1]

In [49]:
print(normal.shape)

(284315, 31)

In [50]:
print(fraud.shape)

(492, 31)

In [51]:
normal.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [52]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [53]:
ccdf.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [54]:
normal_sample=normal.sample(n=492)

<h4>Creating Balanced Dataset :</h4>

In [55]:
new_file=pd.concat([normal_sample,fraud],axis=0)

In [56]:
new_file.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
37001,38764.0,-0.370598,0.571503,1.785542,0.290973,0.320251,0.217086,-1.339675,-1.435671,0.684152,...,1.405158,-0.868439,-1.331882,-0.387142,1.003597,-0.411950,0.262916,0.231292,9.99,0
251172,155254.0,-0.744711,0.420181,0.122854,-2.287762,0.231387,0.029968,-0.304830,0.602973,-1.311361,...,0.370358,0.818207,-0.305536,-0.001344,0.101288,-0.197817,0.003478,0.080549,24.99,0
166569,118169.0,-1.300136,1.194822,1.445643,0.402648,0.640644,0.999781,0.367688,0.398621,-0.182778,...,-0.325518,-0.617203,-0.132975,-0.031702,0.540322,-0.653964,0.575250,0.296123,24.40,0
218279,141246.0,2.074233,-0.895670,-1.489598,-0.327364,-0.315111,-0.192639,-0.447182,0.034975,-0.397228,...,-0.584027,-1.320251,0.324288,0.249545,-0.319898,0.069590,-0.065896,-0.060133,46.09,0
42961,41314.0,-0.868110,0.523556,1.732978,0.954978,0.492438,0.102452,1.087158,-0.746143,0.762213,...,-0.211578,0.141542,0.001694,0.064962,-0.559637,-0.570826,-0.878422,-0.489870,30.04,0
110555,71872.0,-3.331873,-3.011615,-0.494158,-0.846347,6.492788,0.844762,-2.248596,0.840917,0.983264,...,-0.368650,-0.449197,-0.722416,1.025658,-0.324111,0.001118,0.617109,-0.161635,12.31,0
144357,86059.0,-0.312240,0.782527,0.658743,-0.625691,0.840692,-0.106744,-0.745745,-1.446916,-0.127382,...,1.184402,-1.827874,-0.960120,-0.892927,0.887495,0.097455,0.119534,0.192406,1.79,0
172089,120954.0,-0.149937,-0.110410,-0.292518,-1.930318,-0.834613,0.146244,1.989810,-0.732146,-1.051190,...,-0.099619,-0.039282,0.069759,0.610975,-0.452089,-0.557921,-0.177766,-0.239548,321.50,0
266122,162195.0,-0.486100,0.717031,0.392562,-0.881145,1.031163,-0.320895,1.607573,-0.485751,0.236423,...,-0.260511,-0.305893,-0.303885,-0.604291,0.020973,-0.142989,-0.330309,-0.312114,75.46,0
126170,77950.0,1.179409,-0.521150,0.980805,-0.680598,-1.345802,-0.585016,-0.767885,0.188722,2.073133,...,0.015608,0.238438,0.056140,0.373972,0.321815,-0.670931,0.098565,0.031247,1.00,0

In [57]:
new_file['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [58]:
new_file.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94749.168699,-0.110804,-0.064273,0.064047,-0.075763,0.136337,0.145960,0.026834,0.005671,0.026708,...,-0.019862,0.042954,-0.013884,0.010699,0.011325,0.026438,-0.000898,0.016522,0.001289,99.891809
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [59]:
X=new_file.drop(columns='Class',axis=1)

In [60]:
Y=new_file['Class']

<h4>Once DataFrame is ready we split it into training and testing</h4>
<h5>Train Data : 80% </h5>
<h5>Test Data :  20%</h5>

In [61]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [62]:
model=LogisticRegression(max_iter=100)

In [63]:
model.fit(X_train,y_train)

LogisticRegression()

<h4>Making Predictions :</h4>

In [64]:
X_train_prediction=model.predict(X_train)

In [65]:
training_data_acuracy=accuracy_score(X_train_prediction,y_train)*100

<h4>Training Accuracy :</h4>

In [66]:
print(f"Training Data Accuracy: {training_data_acuracy}%")

Training Data Accuracy: 93.90088945362135%

In [67]:
X_test_prediction=model.predict(X_test)

In [68]:
test_data_accuracy=accuracy_score(X_test_prediction,y_test)*100

<h4>Testing Accuracy :</h4>

In [69]:
print(f"Test Data Accuracy: {test_data_accuracy}%")

Test Data Accuracy: 91.37055837563452%